Fix/accessibility docs
ONSdigital/business-index-ui pull request #48
Opened 2018-05-21 08:38 UTC by ONS-Tom

- Add `ACCESSIBILITY` README
- Add `react-document-title` dependancy to use a specific document title per page
- Defer `jquery` script in the `index.html` to reduce page load times (tested using Lighthouse)

2018-05-21 09:42 UTC, willis7 commented
You have committed code which is unrelated to this PR (Fix slow loading scripts in index.html). You should remove that change and attach it to its own PR so it can be tested properly. I would also add some instructions on how you tested with some evidence.

Why use Lighthouse? How do you plan on using it in Jenkins? Can it be run browserless? It would be good to get that information in the PR to help the reviewer understand the decision process.

2018-05-21 11:50 UTC, willis7 commented
A revert would have been better than a new commit.

https://www.atlassian.com/git/tutorials/undoing-changes/git-revert

You still need to revert the JQuery changes.

2018-07-02 11:05 UTC, willis7 requested changes
changes in comments ;-)

2018-09-21 22:28 UTC, awharris approved these changes

2018-09-21 22:28 UTC, merged